### ISSUE TITLE
Cannot find an overload for "AcquireTokenAsync" and the argument count: "4".

### ISSUE THREAD

**Issue by GavinEke** [Canthv0/CloudConnect#1]
I have started to get the following error messages when attempting to connect to Exchange Online. If I run `Connect-EXO` I get following messages:

```
Cannot find an overload for "AcquireTokenAsync" and the argument count: "4".
At C:\Program Files\WindowsPowerShell\Modules\CloudConnect\1.1.2\CloudConnect.psm1:87 char:17
+ ...             $Result = $authContext.AcquireTokenAsync($resourceAppIdUR ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest
 
You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\CloudConnect\1.1.2\Services\Connect-EXO.ps1:38 char:5
+     $UserId = ($Token.Result.UserInfo.DisplayableId).tostring()
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
New-Object : Exception calling ".ctor" with "2" argument(s): "Cannot process argument because the value of argument "userName" is not valid. Change the value of the "userName" argument and run the operation again."
At C:\Program Files\WindowsPowerShell\Modules\CloudConnect\1.1.2\Services\Connect-EXO.ps1:42 char:18
+ ... Credtoken = New-Object System.Management.Automation.PSCredential -Arg ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand
```

Not sure if the following helps with troubleshooting but if I run `Get-ServiceToken -service exo`, I get the following output:

```
Cannot find an overload for "AcquireTokenAsync" and the argument count: "4".
At C:\Program Files\WindowsPowerShell\Modules\CloudConnect\1.1.2\CloudConnect.psm1:87 char:17
+ ...             $Result = $authContext.AcquireTokenAsync($resourceAppIdUR ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest
 


Result                 : 
Id                     : 20929
Exception              : System.AggregateException: One or more errors occurred. ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalSilentTokenAcquisitionException: Failed to acquire token silently. Call method AcquireToken
                            at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenSilentHandler.SendTokenRequestAsync()
                            at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<RunAsync>d__0.MoveNext()
                         --- End of stack trace from previous location where exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenSilentCommonAsync>d__10.MoveNext()
                         --- End of stack trace from previous location where exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenSilentAsync>d__56.MoveNext()
                            --- End of inner exception stack trace ---
                         ---> (Inner Exception #0) Microsoft.IdentityModel.Clients.ActiveDirectory.AdalSilentTokenAcquisitionException: Failed to acquire token silently. Call method AcquireToken
                            at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenSilentHandler.SendTokenRequestAsync()
                            at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<RunAsync>d__0.MoveNext()
                         --- End of stack trace from previous location where exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenSilentCommonAsync>d__10.MoveNext()
                         --- End of stack trace from previous location where exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenSilentAsync>d__56.MoveNext()
                         	ErrorCode: failed_to_acquire_token_silently<---
                         
Status                 : Faulted
IsCanceled             : False
IsCompleted            : True
CreationOptions        : None
AsyncState             : 
IsFaulted              : True
AsyncWaitHandle        : System.Threading.ManualResetEvent
CompletedSynchronously : False
```

Let me know if there is any more information I can provide to troubleshoot the issue.

Kind Regards,
-Gavin

**Comment by chrish012** [comment]
Hi GavinEke, what version of the AzureAD module do you have installed?  It looks like these cmdlets rely on version 2.0.2.16 specifically.

**Comment by GavinEke** [comment]
Hi Chris,

The currently avalible version on this server is as below which include 2.0.2.16, I do believe this is something unique to my environment as it works on other computers and servers, it also previously worked on this machine but I cannot identify what has changed and am having trouble identifing the root cause.

ModuleType Version    Name
---------- -------    ----
Binary     2.0.2.50   AzureAD
Binary     2.0.2.26   AzureAD
Binary     2.0.2.16   AzureAD
Binary     2.0.1.16   AzureAD

I don't think this is a module specific error so I might close this issue. Thanks for the comment though, I also like your pull request and hope it gets merged.

-Gavin
